name: Building Package using Conda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_CMD_PREFIX: "conda build . --no-test --python="


jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest]
        env:
          - CONDA_PY: "3.8" 
          - CONDA_PY: "3.9" 
          - CONDA_PY: "3.10" 

    environment: anaconda_build

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
          miniconda-version: "latest"
          auto-update-conda: true
          channels: conda-forge, fredboudon
          auto-activate-base: true
          activate-environment: "buildenv"
          conda-build-version: "*"
          mamba-version: "*"

    - name: Setup anaconda-client
      run: |
        echo "Install anaconda-client"
        conda info
        mamba install -y -q anaconda-client
        anaconda --version

    - name: Build 
      id: build
      env:
          CONDA_PY: ${{ matrix.env.CONDA_PY }}
          BUILD_CMD: "${{ env.BUILD_CMD_PREFIX }}${{ matrix.env.CONDA_PY }}"
      run: |
        # Build
        if [[ "$CONDA_PY" = "" ]]; then
          echo "CONDA_PY is not defined"
          exit -1
        fi

        $BUILD_CMD

    - name: Set UUID
      id: generate-uuid
      uses: filipstefansson/uuid-action@v1.1

    - name: Login
      env:
          ANACONDA_LOGIN: ${{ secrets.ANACONDA_LOGIN }}
          ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
          SESSION_UID: ${{ steps.generate-uuid.outputs.uuid }}
      run: |
        # Login
        if [[ "$ANACONDA_LOGIN" = "" ]]; then
          echo "ANACONDA_LOGIN is not defined"
          exit -1
        fi
        if [[ "$SESSION_UID" = "" ]]; then
          echo "SESSION_UID is not defined"
          exit -1
        fi

        echo "SESSION_UID=$SESSION_UID"

        anaconda login --username $ANACONDA_LOGIN --password $ANACONDA_PASSWORD --hostname $SESSION_UID

    - name: Deploy
      env:
          ANACONDA_OWNER: ${{ secrets.ANACONDA_OWNER }}
          BUILD_OUTPUT_CMD: "${{ env.BUILD_CMD_PREFIX }}${{ matrix.env.CONDA_PY }} --output"
      run: |
        # Deploy
        if [[ "$ANACONDA_OWNER" = "" ]]; then
          echo "ANACONDA_OWNER is not defined"
          exit -1
        fi

        export PACKAGE_NAME=`$BUILD_OUTPUT_CMD`

        if [[ "$BUILD_OUTPUT" = "" ]]; then
          echo "PACKAGE_NAME is not defined"
          exit -1
        fi

        anaconda upload --skip-existing $PACKAGE_NAME -u $ANACONDA_OWNER --no-progress

  build-win:
    if: ${{ false }}  # disable for now
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019]
        env:
          - CONDA_PY: "3.8" 
          - CONDA_PY: "3.9" 
          - CONDA_PY: "3.10" 

    environment: anaconda_build

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
          miniconda-version: "latest"
          auto-update-conda: true
          channels: conda-forge, fredboudon
          auto-activate-base: true
          activate-environment: ""
          conda-build-version: "*"
          mamba-version: "*"

    - name: Setup anaconda-client
      shell: cmd /C CALL {0} 
      run: |
        ECHO "Install anaconda-client"
        call conda activate base
        mamba install -y -q anaconda-client

    - name: Setup Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
          vsversion: "2019"

    - name: Build
      id: build
      env:
          CONDA_PY: ${{ matrix.env.CONDA_PY }}
          BUILD_CMD: "${{ env.BUILD_CMD_PREFIX }}${{ matrix.env.CONDA_PY }}"
      shell: cmd /C CALL {0} 
      run: |
        ECHO Conda build with CMD and Python %CONDA_PY%
        call conda activate base

        ECHO BUILD
        ECHO BUILD_CMD="%BUILD_CMD%"
        %BUILD_CMD%

    - name: Set UUID
      id: generate-uuid
      uses: filipstefansson/uuid-action@v1.1

    - name: Login
      env:
          ANACONDA_LOGIN: ${{ secrets.ANACONDA_LOGIN }}
          ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
          SESSION_UID: ${{ steps.generate-uuid.outputs.uuid }}
      shell: cmd /C CALL {0}
      run: |
        IF not defined ANACONDA_LOGIN (
          echo "ANACONDA_LOGIN is not defined"
          exit -1
        )
        IF not defined SESSION_UID (
          echo "SESSION_UID is not defined"
          exit -1
        )
        ECHO SESSION_UID=%SESSION_UID%

        ECHO LOGIN
        call conda activate base
        anaconda login --username %ANACONDA_LOGIN% --password %ANACONDA_PASSWORD% --hostname %SESSION_UID%

    - name: Deploy
      env:
          ANACONDA_OWNER: ${{ secrets.ANACONDA_OWNER }}
          BUILD_OUTPUT_CMD: "${{ env.BUILD_CMD_PREFIX }}${{ matrix.env.CONDA_PY }} --output"

      shell: cmd /C CALL {0}
      run: |
        if not defined ANACONDA_OWNER (
          echo "ANACONDA_OWNER is not defined"
          exit 1
        )

        call conda activate base
        ECHO Retrieve output

        FOR /f  %%i IN ('call %BUILD_OUTPUT_CMD%') DO (
          SET PACKAGE_NAME=%%i
        )

        IF  not defined PACKAGE_NAME (
          ECHO "PACKAGE_NAME is not defined"
          EXIT 1
        )
        ECHO PACKAGE_NAME="%PACKAGE_NAME%"

        ECHO DEPLOY
        anaconda upload --skip-existing %PACKAGE_NAME% -u %ANACONDA_OWNER% --no-progress

